// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class Cartoes
    {
        public int CartoesID { get; set; }
        public string CPF_CNPJ { get; set; }
        public DateTime Datas { get; set; }
        public decimal? DividaConsolidada { get; set; }
        public decimal? LimiteAtribuido { get; set; }
        public decimal? LimiteDisponivel { get; set; }
        public decimal? LimiteUtilizado { get; set; }
    }
}