// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class ChequeEspecial
    {
        public int ChequeEspecialID { get; set; }
        public string CPF_CNPJ { get; set; }
        public decimal? ValorLimiteCreditoContratato { get; set; }
        public decimal? ValorSaldoDevedor { get; set; }
        public decimal? ValorUtilizado { get; set; }
        public decimal? QuantidadeDiasUtilizacao { get; set; }
    }
}