// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class Endividamento
    {
        public int EndividamentoID { get; set; }
        public string CPF_CNPJ { get; set; }
        public string OrigemPrejuizo { get; set; }
        public string SubmodalidadeBacen { get; set; }
        public int? DiasAtrasoParcela { get; set; }
        public decimal? SaldoDevedorDiario { get; set; }
    }
}