// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class EndividamentoInterno
    {
        public int EndividamentoInternoID { get; set; }
        public string CPF_CNPJ { get; set; }
        public string ModalidadeProduto { get; set; }
        public int QuantidadeParcelas { get; set; }
        public int QuantidadeParcelasAbertas { get; set; }
        public decimal ValorContrato { get; set; }
        public decimal SaldoDevedorDiario { get; set; }
        public decimal INAD15 { get; set; }
        public decimal INAD90 { get; set; }
    }
}