// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class Garantias
    {
        public int GarantiasID { get; set; }
        public string CPF_CNPJ { get; set; }
        public string GarantiaEnquadramento { get; set; }
        public string TipoGarantiaEnquadramento { get; set; }
        public decimal? ValorTotalGarantia { get; set; }
    }
}