// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class LimiteCCL
    {
        public int LimiteCCLID { get; set; }
        public string CPF_CNPJ { get; set; }
        public string ModalidadeBacen { get; set; }
        public string DataVigenciaLimite { get; set; }
        public string NivelRiscoCliente { get; set; }
        public string DescricaoNivelRiscoBACEN { get; set; }
        public string DescricaoNivelRiscoCRL { get; set; }
        public decimal ValorLimiteConcedido { get; set; }
        public decimal ValorLimiteUtilizado { get; set; }
    }
}