// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class MediaEntradaSemestral
    {
        public int MediaEntradaSemestralID { get; set; }
        public string CPF_CNPJ { get; set; }
        public DateTime Datas { get; set; }
        public decimal LancamentoCredito { get; set; }
    }
}