// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class PatrimonioCadastroAssociado
    {
        public int PatrimonioCadastroAssociadoID { get; set; }
        public string CPF_CNPJ { get; set; }
        public string Nome { get; set; }
        public DateTime DataInicioRelacionamento { get; set; }
        public DateTime DataUltimaRenovacaoCadastral { get; set; }
        public decimal ValorBemImovel { get; set; }
        public decimal ValorBemMovel { get; set; }
        public decimal RendaBrutaMensal { get; set; }
        public DateTime DataNascimento { get; set; }
        public int Idade { get; set; }
    }
}