// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class PreAprovado
    {
        public int PreAprovadoID { get; set; }
        public string CPF_CNPJ { get; set; }
        public decimal ValorLimiteContratado { get; set; }
        public decimal ValorLimiteUtilizado { get; set; }
    }
}