// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class Roles
    {
        public Roles()
        {
            Users = new HashSet<Users>();
        }

        public int RoleCode { get; set; }
        public string TipoDeUsuario { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}