// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class Tarifas
    {
        public int TarifasID { get; set; }
        public string CPF_CNPJ { get; set; }
        public decimal Tarifa { get; set; }
    }
}