// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class UtilizacaoLimiteCredito
    {
        public int UtilizacaoLimiteCreditoID { get; set; }
        public string CPF_CNPJ { get; set; }
        public decimal? ValorLimiteCreditoContratato { get; set; }
        public decimal? ValorSaldoDevedorFinalLimiteUtilizado { get; set; }
        public decimal? QuantidadeDiasUtilizacaoLimiteCredito { get; set; }
    }
}