// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SicoobTeste.Models
{
    public partial class ValorLimiteCRL
    {
        public int ValorLimiteCRLID { get; set; }
        public string CPF_CNPJ { get; set; }
        public decimal? ValorLimiteConcedidoClienteCRL { get; set; }
        public decimal? ValorLimiteUtilizadoClienteCLS { get; set; }
    }
}