// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SicoobTeste.Models
{
    public partial class SicoobTesteContext : DbContext
    {
        public SicoobTesteContext()
        {
        }

        public SicoobTesteContext(DbContextOptions<SicoobTesteContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AplicacaoCota> AplicacaoCota { get; set; }
        public virtual DbSet<Cartoes> Cartoes { get; set; }
        public virtual DbSet<CartoesTrimestre> CartoesTrimestre { get; set; }
        public virtual DbSet<Endividamento> Endividamento { get; set; }
        public virtual DbSet<EndividamentoExterno> EndividamentoExterno { get; set; }
        public virtual DbSet<EndividamentoInterno> EndividamentoInterno { get; set; }
        public virtual DbSet<IAP> IAP { get; set; }
        public virtual DbSet<LimiteCredito> LimiteCredito { get; set; }
        public virtual DbSet<MargemContribuicao> MargemContribuicao { get; set; }
        public virtual DbSet<MediaEntradaSemestral> MediaEntradaSemestral { get; set; }
        public virtual DbSet<MediaEntradaTrimestral> MediaEntradaTrimestral { get; set; }
        public virtual DbSet<PatrimonioCadastroAssociado> PatrimonioCadastroAssociado { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SerasaDetalhado> SerasaDetalhado { get; set; }
        public virtual DbSet<Tarifas> Tarifas { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AplicacaoCota>(entity =>
            {
                entity.Property(e => e.AplicacaoCotaID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.SaldoClienteContaCapitalDiario).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SaldoDiarioRDC).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<Cartoes>(entity =>
            {
                entity.Property(e => e.CartoesID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DividaConsolidada).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LimiteAtribuido).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LimiteDisponivel).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LimiteUtilizado).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<CartoesTrimestre>(entity =>
            {
                entity.Property(e => e.CartoesTrimestreID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DividaConsolidada).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LimiteAtribuido).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LimiteDisponivel).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LimiteUtilizado).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<Endividamento>(entity =>
            {
                entity.Property(e => e.EndividamentoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.OrigemPrejuizo)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.SaldoDevedorDiario).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SubmodalidadeBacen)
                    .IsRequired()
                    .HasMaxLength(120)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<EndividamentoExterno>(entity =>
            {
                entity.Property(e => e.EndividamentoExternoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Prejuizo).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SaldoDevedor).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SubmodalidadeBacen)
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property(e => e.ValorVencerApos360Dias).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ValorVencerAte360Dias).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ValorVencido).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<EndividamentoInterno>(entity =>
            {
                entity.Property(e => e.EndividamentoInternoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ModalidadeProduto)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SaldoDevedorDiario).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ValorContrato).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<IAP>(entity =>
            {
                entity.Property(e => e.IAPID).ValueGeneratedNever();

                entity.Property(e => e.Automovel)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.CartaoCredito)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CartaoDebito)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.ChequeEspecial)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Cobrança)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Consorcio)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.ContaCapital)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.ContaCorrenteInativa)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.CreditoRural)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.DebitoAutomaticoEfetivado)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Emprestimo)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Financiamento)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Investimento)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.LCA)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.LCI)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.MobileBanking)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Moto)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.PacoteTarifas)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.PreAprovado)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Previdencia)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.ProdutoRDC)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.ProdutorRural)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SIPAG)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SeguroAuto)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SeguroGeral)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SeguroMassificados)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SeguroRural)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SeguroVida)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SeguroVidaPF_PJ)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Servicos)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SicoobEmpresarial)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SicoobNet)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.TituloDescontado)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.VidaPrestamista)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<LimiteCredito>(entity =>
            {
                entity.Property(e => e.LimiteCreditoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LimiteCreditoContrato).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SaldoDevedorFinal).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<MargemContribuicao>(entity =>
            {
                entity.Property(e => e.MargemContribuicaoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ResultadoAssociados).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<MediaEntradaSemestral>(entity =>
            {
                entity.HasKey(e => new { e.MediaEntradaSemestralID, e.CPF_CNPJ })
                    .HasName("PK_MediaEntradaSemestralID");

                entity.Property(e => e.CPF_CNPJ)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LancamentoCredito).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<MediaEntradaTrimestral>(entity =>
            {
                entity.Property(e => e.MediaEntradaTrimestralID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LancamentoCredito).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<PatrimonioCadastroAssociado>(entity =>
            {
                entity.Property(e => e.PatrimonioCadastroAssociadoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataInicioRelacionamento).HasColumnType("date");

                entity.Property(e => e.DataUltimaRenovacaoCadastral).HasColumnType("date");

                entity.Property(e => e.ValorBemMovel).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<Roles>(entity =>
            {
                entity.HasKey(e => e.RoleCode)
                    .HasName("PK_RoleCode");

                entity.Property(e => e.RoleCode).ValueGeneratedNever();

                entity.Property(e => e.TipoDeUsuario)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<SerasaDetalhado>(entity =>
            {
                entity.Property(e => e.SerasaDetalhadoID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Tarifas>(entity =>
            {
                entity.Property(e => e.TarifasID).ValueGeneratedNever();

                entity.Property(e => e.CPF_CNPJ)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Tarifa).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.Property(e => e.UsersID).ValueGeneratedNever();

                entity.Property(e => e.DataDeCriacao).HasColumnType("date");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Sobrenome)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.RoleCodeNavigation)
                    .WithMany(p => p.Users)
                    .HasForeignKey(d => d.RoleCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_RoleCode");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}